alias gcln="git clone"
alias gst="git status"
alias ga="git add"
alias gcmt="git commit"
alias branch="git checkout"
alias gbc="git checkout -b"
alias land="git push"
alias rebase="git rebase"
alias merge="git merge"
alias sync="git pull"
alias stash="git stash"
alias pop="git stash pop"
alias lb="git branch"
alias db="git branch -d"
alias dbf="git branch -D"

alias bsh="vi ~/.bashrc"
alias ubsh="source ~/.bashrc"
